### ISSUE TITLE
OPTIONS /cloudfoundryapplication gives 500 error

### ISSUE THREAD

**Issue by ukabu** [stfsy/node-cloudfoundry-actuator#1]
We are getting `"OPTIONS /cloudfoundryapplication HTTP/1.1" 500 0 0` when running on PAS 2.3.
Since OPTIONS returns an error, the /cloudfoundryapplication/health is never requested.

using `"express-cloudfoundry-actuator-middleware": "^1.2.0"`

**Comment by ukabu** [comment]
Looks like at the following line it's expecting an array but gets an object (there is no forEach in Object): 
https://github.com/stfsy/node-cloudfoundry-actuator/blob/0b00bff15888d03798a04fce475a6b62cb97963f/lib/endpoints/discovery.js#L35

**Comment by stfsy** [comment]
@ukabu thanks for having a look. so i guess it's because of this line: https://github.com/stfsy/node-cloudfoundry-actuator/blob/master/lib/registry.js#L13

**Comment by ukabu** [comment]
yeah, but in _addEndpoint, it also use it as an object. Using the endpoint path as the key. So I guess that at https://github.com/stfsy/node-cloudfoundry-actuator/blob/0b00bff15888d03798a04fce475a6b62cb97963f/lib/endpoints/discovery.js#L35, the object properties must be iterated.

**Comment by stfsy** [comment]
@ukabu the contributors problem should be fixed in the **dev** branch 

i'd also change the **handle** method of https://github.com/stfsy/node-cloudfoundry-actuator/blob/dev/lib/index.js#L20 to have a https://github.com/senchalabs/connect like interface

```js
    handle(req, res, next) {
        this._trace(req, res)
        return this._handle(req, res, next)
    }
```

will run a test on our pcf runtime tomorrow

**Comment by stfsy** [comment]
allright @ukabu i was finally able to run a test on run.pivotal.io and release **v3.0.0**
